[passwords]
# Follow the rule: username = "password"
finetune = "genai@2024"
bob_bar = "mycrazypw"

[connections.postgresql]
dialect = "postgresql"
host = "finetune-ai.postgres.database.azure.com"
port = "5432"
database = "Fintune"
username = "finetune"
password = "genai#2024"

[database]
credentials  = '''{
  "type": "service_account",
  "project_id": "project-sirius-424906",
  "private_key_id": "01888578fa0653c614add7de024c0b9aedb03507",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCHJswEujjME/z7\nBWT1WlDNUu5G/yLdabND9pxP5cH53oKGzJgrM6pdk9jdyX0qvD0iO/r9yQ75P2C9\nLlsGGduLkrTNlcSgP7uXyrOoOV3hhJc5axwSssgffHuNOnxpSXHLgwkTtMw747za\nyABzP3379CNF15WvX2DIcE7yaNMfmWg3Fn5SRT/rmylsDiukEsICHW6tMADyD9U9\nHCkMALy6M1pCCRVTDmhP46MIP2oSbG+5T1tUl6DbUagFO/JH57WxmFsgOtkwNP3P\nzt7jE9O4TAYFIDL6D6ny5aZaW/bpafvpBGB9z/tlISS9S253yzpa0fBaQp+yhBnP\nsKOwLNPvAgMBAAECggEAECyJb+tlTq75sITFv0MOtnO9RkvUPVEf/fsuW7VwUFnb\nnwwvDcSCF+7QnkI1s36Rhl5NPD/qhdOa3SkGBaXki0CEWLIatN7LsW+1rmUnIgz/\nGAUEeAxjPLlmA9HC/8qlTqig1nXllyk6+afDvgcUKane6sXRCQrOB07Bc+stkPNb\nZzaTtGxhKOQhP8rSy4fjSru99KxYQkLF7Y/MTFBCdAayULr7FDwmeNTAW3CJomi2\neh9mAFcB/maxS4B9eCfd5pUngCOEInTxEWd0Q2aaEzftHDXADrl+wjbzaUZKCdAR\niztb990E/t/sVDUsExEHxRr1rnoRscfbaJGWV0fecQKBgQC+83wBzMe7fg3FI7iq\nvx1+KXVFDELqjEh+ZVPq9G4xvumK9pf5kr7MH5s928jF+IsNoQ4sDOK7yISwdKxd\nruJRHCoiFeSwx8UvsOKlPYQ/thzErMfAAFjt5ibcREdC4ekVTfRoqshYPmvQQ2f5\nEfWc7iroC+YRxoa3H74FAKwpJwKBgQC1MSEqAY3qneIv9laozV6JYhKUvc2fy2uc\n8aR5GkNuBSQQ68M9AUIbQksIb4K3MpP2pbkRyBTpmN2fqEPSl/+MY/pxqYYpx505\nRLxzQxax0LORxFuS6kG8KDz1GWMpNKRWOgZuNFTvThuvJbmJ9Bx7oxK4fFPdzFfT\ni2PzbL7r+QKBgGT0ZBarhtnIzkzxEtwrSNN/5cFIt0Q8QMOanOB2tJ/WWLEgqL7J\nZ9iRyUjOH3sTaakeAlklwuYXIJgOR2cMZBkP8/KrcopIRCdvtJQ6TuZESTduRflr\n9ZhpexgvfSGOQOYDnfmMeXm2HtgwGxNi/GEoxkSCrfOt62F8BcGtVlg3AoGANiON\n4z0/qECwmuAiGKH0g1w4bRUhYYOojeZt3HmKeE807ZFkbs/3bqmqPcUD67VDHMl7\nuOJtzTaN0ey3By+/fbVJ2bhrjARG6Buvq0j6ePsBDKb9LbKtHYlwXVPOmztNdy4z\nSa59SluuTfEZtSypbg/VwiXz8SvjeiQGI2/0xBECgYEAsvWg13Z1uEHe8x7zutLt\n/4rZI4LAyqNLRDgm0prchy2oz/ZPTnCSh3brq2/Us6RSraZ+64Wq1fe9Svur08u8\nb005uzMK3WDt5qB4U/SjE/JoVwE37GFqYlnAmldDLOdkc+ZkVlRI8+FNJa68NhWx\nTI6FLYW/BCDkl/a982AfzOA=\n-----END PRIVATE KEY-----\n",
  "client_email": "sairam-service-account@project-sirius-424906.iam.gserviceaccount.com",
  "client_id": "115827079310941287252",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sairam-service-account%40project-sirius-424906.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'''
connection_string = "postgresql://postgres:postgres-genai@34.93.64.44/genai"